markdown: redcarpet
highlightet: pygments
permalink: /blog/:year/:title/
relative_permalinks: true
exclude:
  - CNAME
  - LICENSE.noita
  - README.md
  - Gemfile
  - Gemfile.lock

layouts: ./_noita

noita:
  name: mgruener GitHub
  description: Github Page for mgruener
  author:
    name: Michael Gr√ºner
    url: https://mgruener.github.io/
  lang: en
  favicons:
    - /assets/2014/04/21/favicon-152.png
  topbar:
    toggle: Menu
    right:
      - name: About
        url: /about/
      - name: Repositories
        url: /repos/
      - name: Blog
        url: /blog/
      - name: Guides / HOWTOs
        url: /guides/
      - name: Github
        url: https://github.com/mgruener/
        class: small button

compress_html:
  clippings: [html, head, title, base, link, meta, style, body, article, section, nav, aside, h1, h2, h3, h4, h5, h6, hgroup, header, footer, address, p, hr, blockquote, ol, ul, li, dl, dt, dd, figure, figcaption, main, div, table, caption, colgroup, col, tbody, thead, tfoot, tr, td, th]
  endings: [html, head, body, li, dt, dd, p, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
